defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:14-browsers
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS

version: 2.1
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm t
      - run: npm run lint
  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set NPM tokens
          command: echo -e $NPMRC > ~/.npmrc
      - run: npx published

workflows:
  version: 2.1
  ci-cd:
    jobs:
      - test:
          context: org-global
      - publish:
          context: org-global
          requires:
            - test
