defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:14-browsers

version: 2.1
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Test
          command: npm t
      - run:
          name: Lint code
          command: npm run lint

workflows:
  version: 2.1
  ci-cd:
    jobs:
      - test
